In [1]:
from ipynb.fs.full.Equity_Scrape import download_equity
from ipynb.fs.full.Stock_Scrape1 import download_stocks
from ipynb.fs.full.CorporateActions_Scrape1 import download_corporate_actions
from ipynb.fs.full.BhavCopy_Scrape import download_bhavcopy
from ipynb.fs.full.Deliverable_Scrape import download_deliverables
from ipynb.fs.full.ConvertBhavToStock import convertBhavCopyToStock
from ipynb.fs.full.Index_Scrape import download_index
from ipynb.fs.full.RiskFreeRate_Scrape import download_risk_free_rate
from ipynb.fs.full.Revenue_Profit_Scrape import download_revenue_profit

from ipynb.fs.full.Data_Cleaning import data_cleaning
from ipynb.fs.full.CorporateActions import apply_corporate_actions
from ipynb.fs.full.Feature_Creation import calculate_beta, calculate_alpha, add_risk_free_column,create_lower_upper_bands, calculate_band_area, create_dividend, create_index, add_next_day_columns
from ipynb.fs.full.Revenue import create_eps_pe_ratio_revenue_income_expenditure_net_profit
from ipynb.fs.full.GrowthRate import find_gain_loss, close_price_as_percent_of_LV_HV_BA, sequential_increase, sequential_decrease, sequential_increase_percentage, sequential_decrease_percentage, max_min_avg_of_sequential_data, sequential_increase_decrease, generate_dictionary_for_quarterwise_data, generate_dictionary_for_quarterwise_growthrate_data, update_growthrate_for_quarterwise_data, quarter_wise_growthrate

import pandas as pd 
import numpy as np
import os

Equity file already exists
C:\Users\venu\Desktop\Stock Market Analysis\Data\BhavCopies
C:\Users\venu\Desktop\Stock Market Analysis\Data\Deliverables
C:\Users\venu\Desktop\Stock Market Analysis\Data
C:\Users\venu\Desktop\Stock Market Analysis\Data\Stock
C:\Users\venu\Desktop\Stock Market Analysis\Data\Corporate Actions
C:\Users\venu\Desktop\Stock Market Analysis\Data

In [2]:
path = os.getcwd()
datapath = os.path.join(path,"Data")
datapath

'C:\\Users\\venu\\Desktop\\Stock Market Analysis\\Data'

In [3]:
download_equity()

Equity file already exists

In [4]:
security_id = "500002"
company_name = "ABB India Limited,Active"

In [5]:
download_corporate_actions(security_id)

[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324

[WDM] - Driver [C:\Users\venu\.wdm\drivers\chromedriver\win32\88.0.4324.96\chromedriver.exe] found in cache

In [6]:
download_bhavcopy()

[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Driver [C:\Users\venu\.wdm\drivers\chromedriver\win32\88.0.4324.96\chromedriver.exe] found in cache

In [7]:
download_deliverables()

[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Driver [C:\Users\venu\.wdm\drivers\chromedriver\win32\88.0.4324.96\chromedriver.exe] found in cache

In [8]:
download_index()

already present

In [9]:
download_risk_free_rate()

[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Driver [C:\Users\venu\.wdm\drivers\chromedriver\win32\88.0.4324.96\chromedriver.exe] found in cache

C:\Users\venu\Desktop\Stock Market Analysis\RiskFreeRate_Scrape.ipynb:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  "        return driver\n",

In [10]:
download_revenue_profit(security_id,company_name)

[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Driver [C:\Users\venu\.wdm\drivers\chromedriver\win32\88.0.4324.96\chromedriver.exe] found in cache

In [5]:
bhav_df_today = pd.read_csv(os.path.join(datapath,"BhavCopies/19022021.csv"))
deliverables_df_today = pd.read_csv(os.path.join(datapath,"Deliverables/19022021.csv"))
df_stocks_today = convertBhavCopyToStock(bhav_df_today,deliverables_df_today)
df_stocks_today.to_csv(os.path.join(datapath,"BhavConvertedToStock/19022021.csv"),index=None)

In [6]:
modified_stock_path = os.path.join(os.getcwd(),"Data\Stock\mod"+security_id+".csv")
print(modified_stock_path)

C:\Users\venu\Desktop\Stock Market Analysis\Data\Stock\mod500002.csv

In [7]:
modified_stock = pd.read_csv(modified_stock_path) if os.path.exists(modified_stock_path) else pd.DataFrame()
modified_stock

,Date,Unix Date,Open Price,High Price,Low Price,Close Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),...,Expenditure last 8 quarters,Net Profit last 8 quarters,EPS last 8 quarters,p/e,Lower Band,Upper Band,Next Day Open Price,Next Day High Price,Next Day Low Price,Next Day Close Price
0,02-01-2007,1167676200,3735.0,3776.00,3700.00,3714.05,3742.739451,21731,1881,81333471.0,...,-118649.76,9020.52,43.57,NaN,NaN,3714.05,3710.0,3739.00,3645.00,3653.65
1,03-01-2007,1167762600,3710.0,3739.00,3645.00,3653.65,3673.477502,28291,1736,103926352.0,...,-118649.76,9020.52,43.57,NaN,NaN,3653.65,3668.0,3684.00,3625.00,3645.15
2,04-01-2007,1167849000,3668.0,3684.00,3625.00,3645.15,3652.205768,19347,1221,70659225.0,...,-118649.76,9020.52,43.57,NaN,NaN,3645.15,3650.0,3675.00,3576.20,3592.70
3,05-01-2007,1167935400,3650.0,3675.00,3576.20,3592.70,3635.146191,22970,1374,83499308.0,...,-118649.76,9020.52,43.57,NaN,NaN,3592.70,3600.0,3600.00,3505.00,3554.15
4,08-01-2007,1168194600,3600.0,3600.00,3505.00,3554.15,3550.702060,23300,1919,82731358.0,...,-118649.76,9020.52,43.57,NaN,NaN,3554.15,3570.0,3595.00,3500.00,3535.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3463,24-12-2020,1608748200,1205.0,1229.95,1191.00,1207.35,1220.311283,45306,667,55287423.0,...,-118649.76,9020.52,43.57,NaN,NaN,NaN,1225.0,1227.65,1212.00,1219.20
3464,28-12-2020,1609093800,1225.0,1227.65,1212.00,1219.20,1217.518506,6106,587,7434168.0,...,-118649.76,9020.52,43.57,NaN,NaN,NaN,1223.0,1229.10,1195.00,1204.55
3465,29-12-2020,1609180200,1223.0,1229.10,1195.00,1204.55,1212.738685,7026,727,8520702.0,...,-118649.76,9020.52,43.57,NaN,NaN,NaN,1229.0,1239.85,1203.90,1209.95
3466,30-12-2020,1609266600,1229.0,1239.85,1203.90,1209.95,1222.053157,14034,1294,17150294.0,...,-118649.76,9020.52,43.57,NaN,NaN,NaN,1212.0,1217.70,1203.55,1212.15
3467,31-12-2020,1609353000,1212.0,1217.70,1203.55,1212.15,1210.068024,7909,554,9570428.0,...,-118649.76,9020.52,43.57,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
stock_df = download_stocks(security_id)
print(stock_df)

[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324

[WDM] - Driver [C:\Users\venu\.wdm\drivers\chromedriver\win32\88.0.4324.96\chromedriver.exe] found in cache

           Date  Open Price  High Price  Low Price  Close Price          WAP  \
3467 2007-01-02      3735.0     3776.00    3700.00      3714.05  3742.739451
3466 2007-01-03      3710.0     3739.00    3645.00      3653.65  3673.477502
3465 2007-01-04      3668.0     3684.00    3625.00      3645.15  3652.205768
3464 2007-01-05      3650.0     3675.00    3576.20      3592.70  3635.146191
3463 2007-01-08      3600.0     3600.00    3505.00      3554.15  3550.702060
...         ...         ...         ...        ...          ...          ...
4    2020-12-24      1205.0     1229.95    1191.00      1207.35  1220.311283
3    2020-12-28      1225.0     1227.65    1212.00      1219.20  1217.518506
2    2020-12-29      1223.0     1229.10    1195.00      1204.55  1212.738685
1    2020-12-30      1229.0     1239.85    1203.90      1209.95  1222.053157
0    2020-12-31      1212.0     1217.70    1203.55      1212.15  1210.068024

      No.of Shares  No. of Trades  Total Turnover (Rs.)  Deliverable Quantity  \
3467         21731           1881            81333471.0                2454.0
3466         28291           1736           103926352.0                9866.0
3465         19347           1221            70659225.0                7468.0
3464         22970           1374            83499308.0                7808.0
3463         23300           1919            82731358.0                4465.0
...            ...            ...                   ...                   ...
4            45306            667            55287423.0               39978.0
3             6106            587             7434168.0                3091.0
2             7026            727             8520702.0                2293.0
1            14034           1294            17150294.0                4729.0
0             7909            554             9570428.0                2725.0

      % Deli. Qty to Traded Qty  Spread High-Low  Spread Close-Open  \
3467                      11.29            76.00             -20.95
3466                      34.87            94.00             -56.35
3465                      38.60            59.00             -22.85
3464                      33.99            98.80             -57.30
3463                      19.16            95.00             -45.85
...                         ...              ...                ...
4                         88.24            38.95               2.35
3                         50.62            15.65              -5.80
2                         32.64            34.10             -18.45
1                         33.70            35.95             -19.05
0                         34.45            14.15               0.15

          Unixtime
3467  1.167676e+09
3466  1.167763e+09
3465  1.167849e+09
3464  1.167935e+09
3463  1.168195e+09
...            ...
4     1.608748e+09
3     1.609094e+09
2     1.609180e+09
1     1.609267e+09
0     1.609353e+09

[3468 rows x 14 columns]

In [15]:
index_df = pd.read_csv(os.path.join(datapath,"Index.csv"))
corporate_df = pd.read_csv(os.path.join(datapath,"Corporate Actions\\" + "Corporate_Actions_" + security_id + ".csv"))
revenue_df = pd.read_csv(os.path.join(datapath,"Revenue/"+security_id+".csv"))

# Data Cleaning

In [16]:
stock_df = data_cleaning(stock_df,index_df)
stock_df

,Date,Open Price,High Price,Low Price,Close Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),Deliverable Quantity,% Deli. Qty to Traded Qty,Spread High-Low,Spread Close-Open,Unixtime
3467,2007-01-02,3735.0,3776.00,3700.00,3714.05,3742.739451,21731,1881,81333471.0,2454.0,11.29,76.00,-20.95,1.167676e+09
3466,2007-01-03,3710.0,3739.00,3645.00,3653.65,3673.477502,28291,1736,103926352.0,9866.0,34.87,94.00,-56.35,1.167763e+09
3465,2007-01-04,3668.0,3684.00,3625.00,3645.15,3652.205768,19347,1221,70659225.0,7468.0,38.60,59.00,-22.85,1.167849e+09
3464,2007-01-05,3650.0,3675.00,3576.20,3592.70,3635.146191,22970,1374,83499308.0,7808.0,33.99,98.80,-57.30,1.167935e+09
3463,2007-01-08,3600.0,3600.00,3505.00,3554.15,3550.702060,23300,1919,82731358.0,4465.0,19.16,95.00,-45.85,1.168195e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,2020-12-24,1205.0,1229.95,1191.00,1207.35,1220.311283,45306,667,55287423.0,39978.0,88.24,38.95,2.35,1.608748e+09
3,2020-12-28,1225.0,1227.65,1212.00,1219.20,1217.518506,6106,587,7434168.0,3091.0,50.62,15.65,-5.80,1.609094e+09
2,2020-12-29,1223.0,1229.10,1195.00,1204.55,1212.738685,7026,727,8520702.0,2293.0,32.64,34.10,-18.45,1.609180e+09
1,2020-12-30,1229.0,1239.85,1203.90,1209.95,1222.053157,14034,1294,17150294.0,4729.0,33.70,35.95,-19.05,1.609267e+09
0,2020-12-31,1212.0,1217.70,1203.55,1212.15,1210.068024,7909,554,9570428.0,2725.0,34.45,14.15,0.15,1.609353e+09

# Applying Corporate Actions

In [17]:
stock_df = apply_corporate_actions(stock_df,corporate_df)
stock_df

,Date,Open Price,High Price,Low Price,Close Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),Deliverable Quantity,% Deli. Qty to Traded Qty,Spread High-Low,Spread Close-Open,Unixtime
3467,2007-01-02,3735.0,3776.00,3700.00,3714.05,3742.739451,21731,1881,81333471.0,2454.0,11.29,76.00,-20.95,1.167676e+09
3466,2007-01-03,3710.0,3739.00,3645.00,3653.65,3673.477502,28291,1736,103926352.0,9866.0,34.87,94.00,-56.35,1.167763e+09
3465,2007-01-04,3668.0,3684.00,3625.00,3645.15,3652.205768,19347,1221,70659225.0,7468.0,38.60,59.00,-22.85,1.167849e+09
3464,2007-01-05,3650.0,3675.00,3576.20,3592.70,3635.146191,22970,1374,83499308.0,7808.0,33.99,98.80,-57.30,1.167935e+09
3463,2007-01-08,3600.0,3600.00,3505.00,3554.15,3550.702060,23300,1919,82731358.0,4465.0,19.16,95.00,-45.85,1.168195e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,2020-12-24,1205.0,1229.95,1191.00,1207.35,1220.311283,45306,667,55287423.0,39978.0,88.24,38.95,2.35,1.608748e+09
3,2020-12-28,1225.0,1227.65,1212.00,1219.20,1217.518506,6106,587,7434168.0,3091.0,50.62,15.65,-5.80,1.609094e+09
2,2020-12-29,1223.0,1229.10,1195.00,1204.55,1212.738685,7026,727,8520702.0,2293.0,32.64,34.10,-18.45,1.609180e+09
1,2020-12-30,1229.0,1239.85,1203.90,1209.95,1222.053157,14034,1294,17150294.0,4729.0,33.70,35.95,-19.05,1.609267e+09
0,2020-12-31,1212.0,1217.70,1203.55,1212.15,1210.068024,7909,554,9570428.0,2725.0,34.45,14.15,0.15,1.609353e+09

# Adding Risk Free Rate column

In [18]:
stock_df = add_risk_free_column(stock_df)
stock_df

,Date,Open Price,High Price,Low Price,Close Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),Deliverable Quantity,% Deli. Qty to Traded Qty,Spread High-Low,Spread Close-Open,Unixtime,Rate
0,2007-01-02,3735.0,3776.00,3700.00,3714.05,3742.739451,21731,1881,81333471.0,2454.0,11.29,76.00,-20.95,1.167676e+09,5.07
1,2007-01-03,3710.0,3739.00,3645.00,3653.65,3673.477502,28291,1736,103926352.0,9866.0,34.87,94.00,-56.35,1.167763e+09,5.05
2,2007-01-04,3668.0,3684.00,3625.00,3645.15,3652.205768,19347,1221,70659225.0,7468.0,38.60,59.00,-22.85,1.167849e+09,5.04
3,2007-01-05,3650.0,3675.00,3576.20,3592.70,3635.146191,22970,1374,83499308.0,7808.0,33.99,98.80,-57.30,1.167935e+09,5.05
4,2007-01-08,3600.0,3600.00,3505.00,3554.15,3550.702060,23300,1919,82731358.0,4465.0,19.16,95.00,-45.85,1.168195e+09,5.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3463,2020-12-24,1205.0,1229.95,1191.00,1207.35,1220.311283,45306,667,55287423.0,39978.0,88.24,38.95,2.35,1.608748e+09,0.09
3464,2020-12-28,1225.0,1227.65,1212.00,1219.20,1217.518506,6106,587,7434168.0,3091.0,50.62,15.65,-5.80,1.609094e+09,0.11
3465,2020-12-29,1223.0,1229.10,1195.00,1204.55,1212.738685,7026,727,8520702.0,2293.0,32.64,34.10,-18.45,1.609180e+09,0.10
3466,2020-12-30,1229.0,1239.85,1203.90,1209.95,1222.053157,14034,1294,17150294.0,4729.0,33.70,35.95,-19.05,1.609267e+09,0.08
3467,2020-12-31,1212.0,1217.70,1203.55,1212.15,1210.068024,7909,554,9570428.0,2725.0,34.45,14.15,0.15,1.609353e+09,0.09

# Creating modified index file

In [19]:
create_index()

# Calculating beta column

In [20]:
stock_df = calculate_beta(stock_df)
stock_df

C:\Users\venu\Desktop\Stock Market Analysis\Feature_Creation.ipynb:58: RuntimeWarning: invalid value encountered in true_divide
  "    ind = pd.read_csv(os.path.join(path,\"modIndex.csv\"))\n",

,Date,Open Price,High Price,Low Price,Close Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),Deliverable Quantity,% Deli. Qty to Traded Qty,Spread High-Low,Spread Close-Open,Unixtime,Rate,% Return of Company,Close Price of SP500,% Return of SP500,Beta
0,2007-01-02,3735.0,3776.00,3700.00,3714.05,3742.739451,21731,1881,81333471.0,2454.0,11.29,76.00,-20.95,1.167676e+09,5.07,-1.626257,5318.06,0.570697,0.2831120322165835
1,2007-01-03,3710.0,3739.00,3645.00,3653.65,3673.477502,28291,1736,103926352.0,9866.0,34.87,94.00,-56.35,1.167763e+09,5.05,-1.626257,5348.41,0.570697,0.2830633338415318
2,2007-01-04,3668.0,3684.00,3625.00,3645.15,3652.205768,19347,1221,70659225.0,7468.0,38.60,59.00,-22.85,1.167849e+09,5.04,-0.232644,5319.70,-0.536795,0.28308432555369784
3,2007-01-05,3650.0,3675.00,3576.20,3592.70,3635.146191,22970,1374,83499308.0,7808.0,33.99,98.80,-57.30,1.167935e+09,5.05,-1.438898,5311.68,-0.150760,0.28307037990817313
4,2007-01-08,3600.0,3600.00,3505.00,3554.15,3550.702060,23300,1919,82731358.0,4465.0,19.16,95.00,-45.85,1.168195e+09,5.08,-1.073009,5247.25,-1.212987,0.283094594755211
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3463,2020-12-24,1205.0,1229.95,1191.00,1207.35,1220.311283,45306,667,55287423.0,39978.0,88.24,38.95,2.35,1.608748e+09,0.09,0.696414,17992.01,0.909826,0.16927524167169994
3464,2020-12-28,1225.0,1227.65,1212.00,1219.20,1217.518506,6106,587,7434168.0,3091.0,50.62,15.65,-5.80,1.609094e+09,0.11,0.981488,18164.87,0.960760,0.12186428031372609
3465,2020-12-29,1223.0,1229.10,1195.00,1204.55,1212.738685,7026,727,8520702.0,2293.0,32.64,34.10,-18.45,1.609180e+09,0.10,-1.201608,18218.91,0.297497,0.017374388296995856
3466,2020-12-30,1229.0,1239.85,1203.90,1209.95,1222.053157,14034,1294,17150294.0,4729.0,33.70,35.95,-19.05,1.609267e+09,0.08,0.448300,18284.31,0.358968,0.5232878419258491
3467,2020-12-31,1212.0,1217.70,1203.55,1212.15,1210.068024,7909,554,9570428.0,2725.0,34.45,14.15,0.15,1.609353e+09,0.09,0.181826,18300.10,0.086358,--

# Calculating alpha column

In [21]:
stock_df = calculate_alpha(stock_df)
stock_df

,Date,Open Price,High Price,Low Price,Close Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),Deliverable Quantity,...,Spread Close-Open,Unixtime,Rate,% Return of Company,Close Price of SP500,% Return of SP500,Beta,% YTD of Company,% YTD of SP500,Alpha
0,2007-01-02,3735.0,3776.00,3700.00,3714.05,3742.739451,21731,1881,81333471.0,2454.0,...,-20.95,1.167676e+09,5.07,-1.626257,5318.06,0.570697,0.2831120322165835,-67.363121,271.892570,-147.974
1,2007-01-03,3710.0,3739.00,3645.00,3653.65,3673.477502,28291,1736,103926352.0,9866.0,...,-56.35,1.167763e+09,5.05,-1.626257,5348.41,0.570697,0.2830633338415318,-66.823587,269.782234,-146.81
2,2007-01-04,3668.0,3684.00,3625.00,3645.15,3652.205768,19347,1221,70659225.0,7468.0,...,-22.85,1.167849e+09,5.04,-0.232644,5319.70,-0.536795,0.28308432555369784,-66.746224,271.777920,-147.296
3,2007-01-05,3650.0,3675.00,3576.20,3592.70,3635.146191,22970,1374,83499308.0,7808.0,...,-57.30,1.167935e+09,5.05,-1.438898,5311.68,-0.150760,0.28307037990817313,-66.260751,272.339260,-146.972
4,2007-01-08,3600.0,3600.00,3505.00,3554.15,3550.702060,23300,1919,82731358.0,4465.0,...,-45.85,1.168195e+09,5.08,-1.073009,5247.25,-1.212987,0.283094594755211,-65.894799,276.911144,-147.929
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3463,2020-12-24,1205.0,1229.95,1191.00,1207.35,1220.311283,45306,667,55287423.0,39978.0,...,2.35,1.608748e+09,0.09,0.696414,17992.01,0.909826,0.16927524167169994,0.397565,9.923627,-1.35702
3464,2020-12-28,1225.0,1227.65,1212.00,1219.20,1217.518506,6106,587,7434168.0,3091.0,...,-5.80,1.609094e+09,0.11,0.981488,18164.87,0.960760,0.12186428031372609,-0.578248,8.877575,-1.7567
3465,2020-12-29,1223.0,1229.10,1195.00,1204.55,1212.738685,7026,727,8520702.0,2293.0,...,-18.45,1.609180e+09,0.10,-1.201608,18218.91,0.297497,0.017374388296995856,0.630941,8.554628,0.384047
3466,2020-12-30,1229.0,1239.85,1203.90,1209.95,1222.053157,14034,1294,17150294.0,4729.0,...,-19.05,1.609267e+09,0.08,0.448300,18284.31,0.358968,0.5232878419258491,0.181826,8.166346,-4.12966
3467,2020-12-31,1212.0,1217.70,1203.55,1212.15,1210.068024,7909,554,9570428.0,2725.0,...,0.15,1.609353e+09,0.09,0.181826,18300.10,0.086358,--,0.000000,8.073016,--

# Create Dividend

In [22]:
stock_df = create_dividend(corporate_df,stock_df)
stock_df

,Date,Open Price,High Price,Low Price,Close Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),Deliverable Quantity,...,Unixtime,Rate,% Return of Company,Close Price of SP500,% Return of SP500,Beta,% YTD of Company,% YTD of SP500,Alpha,Dividend Value
0,2007-01-02,3735.0,3776.00,3700.00,3714.05,3742.739451,21731,1881,81333471.0,2454.0,...,1.167676e+09,5.07,-1.626257,5318.06,0.570697,0.2831120322165835,-67.363121,271.892570,-147.974,0.0
1,2007-01-03,3710.0,3739.00,3645.00,3653.65,3673.477502,28291,1736,103926352.0,9866.0,...,1.167763e+09,5.05,-1.626257,5348.41,0.570697,0.2830633338415318,-66.823587,269.782234,-146.81,0.0
2,2007-01-04,3668.0,3684.00,3625.00,3645.15,3652.205768,19347,1221,70659225.0,7468.0,...,1.167849e+09,5.04,-0.232644,5319.70,-0.536795,0.28308432555369784,-66.746224,271.777920,-147.296,0.0
3,2007-01-05,3650.0,3675.00,3576.20,3592.70,3635.146191,22970,1374,83499308.0,7808.0,...,1.167935e+09,5.05,-1.438898,5311.68,-0.150760,0.28307037990817313,-66.260751,272.339260,-146.972,0.0
4,2007-01-08,3600.0,3600.00,3505.00,3554.15,3550.702060,23300,1919,82731358.0,4465.0,...,1.168195e+09,5.08,-1.073009,5247.25,-1.212987,0.283094594755211,-65.894799,276.911144,-147.929,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3463,2020-12-24,1205.0,1229.95,1191.00,1207.35,1220.311283,45306,667,55287423.0,39978.0,...,1.608748e+09,0.09,0.696414,17992.01,0.909826,0.16927524167169994,0.397565,9.923627,-1.35702,0.0
3464,2020-12-28,1225.0,1227.65,1212.00,1219.20,1217.518506,6106,587,7434168.0,3091.0,...,1.609094e+09,0.11,0.981488,18164.87,0.960760,0.12186428031372609,-0.578248,8.877575,-1.7567,0.0
3465,2020-12-29,1223.0,1229.10,1195.00,1204.55,1212.738685,7026,727,8520702.0,2293.0,...,1.609180e+09,0.10,-1.201608,18218.91,0.297497,0.017374388296995856,0.630941,8.554628,0.384047,0.0
3466,2020-12-30,1229.0,1239.85,1203.90,1209.95,1222.053157,14034,1294,17150294.0,4729.0,...,1.609267e+09,0.08,0.448300,18284.31,0.358968,0.5232878419258491,0.181826,8.166346,-4.12966,0.0
3467,2020-12-31,1212.0,1217.70,1203.55,1212.15,1210.068024,7909,554,9570428.0,2725.0,...,1.609353e+09,0.09,0.181826,18300.10,0.086358,--,0.000000,8.073016,--,0.0

In [23]:
# stock_df.to_csv("C:\\Users\\venu\\Desktop\\Stock Market Analysis\\Data\\afterdividend.csv",index=None)

# Calculating eps, pe ratio

In [24]:
stock_df = create_eps_pe_ratio_revenue_income_expenditure_net_profit(revenue_df,stock_df)
stock_df

,Date,Open Price,High Price,Low Price,Close Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),Deliverable Quantity,...,Income last 4 quarters,Expenditure last 4 quarters,Net Profit last 4 quarters,EPS last 4 quarters,Revenue last 8 quarters,Income last 8 quarters,Expenditure last 8 quarters,Net Profit last 8 quarters,EPS last 8 quarters,p/e
0,2007-01-02,3735.0,3776.00,3700.00,3714.05,3742.739451,21731,1881,81333471.0,2454.0,...,85663.1,-61079.9,5474.14,26.83,132104,148761,-118650,9020.52,43.57,NaN
1,2007-01-03,3710.0,3739.00,3645.00,3653.65,3673.477502,28291,1736,103926352.0,9866.0,...,85663.1,-61079.9,5474.14,26.83,132104,148761,-118650,9020.52,43.57,NaN
2,2007-01-04,3668.0,3684.00,3625.00,3645.15,3652.205768,19347,1221,70659225.0,7468.0,...,85663.1,-61079.9,5474.14,26.83,132104,148761,-118650,9020.52,43.57,NaN
3,2007-01-05,3650.0,3675.00,3576.20,3592.70,3635.146191,22970,1374,83499308.0,7808.0,...,85663.1,-61079.9,5474.14,26.83,132104,148761,-118650,9020.52,43.57,NaN
4,2007-01-08,3600.0,3600.00,3505.00,3554.15,3550.702060,23300,1919,82731358.0,4465.0,...,85663.1,-61079.9,5474.14,26.83,132104,148761,-118650,9020.52,43.57,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3463,2020-12-24,1205.0,1229.95,1191.00,1207.35,1220.311283,45306,667,55287423.0,39978.0,...,85663.1,-61079.9,5474.14,26.83,132104,148761,-118650,9020.52,43.57,NaN
3464,2020-12-28,1225.0,1227.65,1212.00,1219.20,1217.518506,6106,587,7434168.0,3091.0,...,85663.1,-61079.9,5474.14,26.83,132104,148761,-118650,9020.52,43.57,NaN
3465,2020-12-29,1223.0,1229.10,1195.00,1204.55,1212.738685,7026,727,8520702.0,2293.0,...,85663.1,-61079.9,5474.14,26.83,132104,148761,-118650,9020.52,43.57,NaN
3466,2020-12-30,1229.0,1239.85,1203.90,1209.95,1222.053157,14034,1294,17150294.0,4729.0,...,85663.1,-61079.9,5474.14,26.83,132104,148761,-118650,9020.52,43.57,NaN
3467,2020-12-31,1212.0,1217.70,1203.55,1212.15,1210.068024,7909,554,9570428.0,2725.0,...,85663.1,-61079.9,5474.14,26.83,132104,148761,-118650,9020.52,43.57,NaN

In [25]:
# stock_df1.to_csv("C:\\Users\\venu\\Desktop\\Stock Market Analysis\\Data\\aftereps.csv", index = None)

# Calculating upper and lower bands

In [26]:
stock_df = create_lower_upper_bands(stock_df)
stock_df

,Date,Unix Date,Open Price,High Price,Low Price,Close Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),...,Net Profit last 4 quarters,EPS last 4 quarters,Revenue last 8 quarters,Income last 8 quarters,Expenditure last 8 quarters,Net Profit last 8 quarters,EPS last 8 quarters,p/e,Lower Band,Upper Band
0,02-01-2007,1167676200,3735.0,3776.00,3700.00,3714.05,3742.739451,21731,1881,81333471.0,...,5474.14,26.83,132104,148761,-118650,9020.52,43.57,NaN,,3714.05
1,03-01-2007,1167762600,3710.0,3739.00,3645.00,3653.65,3673.477502,28291,1736,103926352.0,...,5474.14,26.83,132104,148761,-118650,9020.52,43.57,NaN,,3653.65
2,04-01-2007,1167849000,3668.0,3684.00,3625.00,3645.15,3652.205768,19347,1221,70659225.0,...,5474.14,26.83,132104,148761,-118650,9020.52,43.57,NaN,,3645.15
3,05-01-2007,1167935400,3650.0,3675.00,3576.20,3592.70,3635.146191,22970,1374,83499308.0,...,5474.14,26.83,132104,148761,-118650,9020.52,43.57,NaN,,3592.7
4,08-01-2007,1168194600,3600.0,3600.00,3505.00,3554.15,3550.702060,23300,1919,82731358.0,...,5474.14,26.83,132104,148761,-118650,9020.52,43.57,NaN,,3554.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3463,24-12-2020,1608748200,1205.0,1229.95,1191.00,1207.35,1220.311283,45306,667,55287423.0,...,5474.14,26.83,132104,148761,-118650,9020.52,43.57,NaN,,
3464,28-12-2020,1609093800,1225.0,1227.65,1212.00,1219.20,1217.518506,6106,587,7434168.0,...,5474.14,26.83,132104,148761,-118650,9020.52,43.57,NaN,,
3465,29-12-2020,1609180200,1223.0,1229.10,1195.00,1204.55,1212.738685,7026,727,8520702.0,...,5474.14,26.83,132104,148761,-118650,9020.52,43.57,NaN,,
3466,30-12-2020,1609266600,1229.0,1239.85,1203.90,1209.95,1222.053157,14034,1294,17150294.0,...,5474.14,26.83,132104,148761,-118650,9020.52,43.57,NaN,,
3467,31-12-2020,1609353000,1212.0,1217.70,1203.55,1212.15,1210.068024,7909,554,9570428.0,...,5474.14,26.83,132104,148761,-118650,9020.52,43.57,NaN,,

In [27]:
# stock_df = data_cleaning(stock_df,index_df)
# stock_df = apply_corporate_actions(stock_df,corporate_df)
# stock_df = add_risk_free_column(stock_df)
# create_index()
# stock_df = calculate_beta(stock_df)
# stock_df = calculate_alpha(stock_df)
# stock_df = create_dividend(corporate_df,stock_df)
# stock_df = create_eps_pe_ratio_revenue_income_expenditure_net_profit(revenue_df,stock_df)
# stock_df = create_lower_upper_bands(stock_df)
# stock_df = stock_df.sort_values(by=["Date"],ascending=[True])

In [28]:
# stock_df

In [29]:
stock_df = add_next_day_columns(stock_df)
stock_df

,Date,Unix Date,Open Price,High Price,Low Price,Close Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),...,Expenditure last 8 quarters,Net Profit last 8 quarters,EPS last 8 quarters,p/e,Lower Band,Upper Band,Next Day Open Price,Next Day High Price,Next Day Low Price,Next Day Close Price
0,02-01-2007,1167676200,3735.0,3776.00,3700.00,3714.05,3742.739451,21731,1881,81333471.0,...,-118650,9020.52,43.57,NaN,,3714.05,3710.0,3739.00,3645.00,3653.65
1,03-01-2007,1167762600,3710.0,3739.00,3645.00,3653.65,3673.477502,28291,1736,103926352.0,...,-118650,9020.52,43.57,NaN,,3653.65,3668.0,3684.00,3625.00,3645.15
2,04-01-2007,1167849000,3668.0,3684.00,3625.00,3645.15,3652.205768,19347,1221,70659225.0,...,-118650,9020.52,43.57,NaN,,3645.15,3650.0,3675.00,3576.20,3592.70
3,05-01-2007,1167935400,3650.0,3675.00,3576.20,3592.70,3635.146191,22970,1374,83499308.0,...,-118650,9020.52,43.57,NaN,,3592.7,3600.0,3600.00,3505.00,3554.15
4,08-01-2007,1168194600,3600.0,3600.00,3505.00,3554.15,3550.702060,23300,1919,82731358.0,...,-118650,9020.52,43.57,NaN,,3554.15,3570.0,3595.00,3500.00,3535.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3463,24-12-2020,1608748200,1205.0,1229.95,1191.00,1207.35,1220.311283,45306,667,55287423.0,...,-118650,9020.52,43.57,NaN,,,1225.0,1227.65,1212.00,1219.20
3464,28-12-2020,1609093800,1225.0,1227.65,1212.00,1219.20,1217.518506,6106,587,7434168.0,...,-118650,9020.52,43.57,NaN,,,1223.0,1229.10,1195.00,1204.55
3465,29-12-2020,1609180200,1223.0,1229.10,1195.00,1204.55,1212.738685,7026,727,8520702.0,...,-118650,9020.52,43.57,NaN,,,1229.0,1239.85,1203.90,1209.95
3466,30-12-2020,1609266600,1229.0,1239.85,1203.90,1209.95,1222.053157,14034,1294,17150294.0,...,-118650,9020.52,43.57,NaN,,,1212.0,1217.70,1203.55,1212.15
3467,31-12-2020,1609353000,1212.0,1217.70,1203.55,1212.15,1210.068024,7909,554,9570428.0,...,-118650,9020.52,43.57,NaN,,,NaN,NaN,NaN,NaN

In [30]:
modified_stock = modified_stock.append(stock_df,ignore_index=True)

In [31]:
modified_stock.to_csv(modified_stock_path,index=None)

In [22]:
modified_GRstock_path = os.path.join(os.getcwd(),"Data\Stock\mod"+security_id+"GR.csv")
print(modified_GRstock_path)

C:\Users\venu\Desktop\Stock Market Analysis\Data\Stock\mod500002GR.csv

In [23]:
modified_stockGR = pd.read_csv(modified_GRstock_path) if os.path.exists(modified_GRstock_path) else pd.DataFrame()
modified_stockGR

Empty DataFrame
Columns: []
Index: []

In [24]:
mstock_df = pd.read_csv(modified_stock_path)
mstock_df

,Date,Unix Date,Open Price,High Price,Low Price,Close Price,WAP,No.of Shares,No. of Trades,Total Turnover (Rs.),...,Expenditure last 8 quarters,Net Profit last 8 quarters,EPS last 8 quarters,p/e,Lower Band,Upper Band,Next Day Open Price,Next Day High Price,Next Day Low Price,Next Day Close Price
0,02-01-2007,1167676200,3735.0,3776.00,3700.00,3714.05,3742.739451,21731,1881,81333471.0,...,-118649.76,9020.52,43.57,NaN,NaN,3714.05,3710.0,3739.00,3645.00,3653.65
1,03-01-2007,1167762600,3710.0,3739.00,3645.00,3653.65,3673.477502,28291,1736,103926352.0,...,-118649.76,9020.52,43.57,NaN,NaN,3653.65,3668.0,3684.00,3625.00,3645.15
2,04-01-2007,1167849000,3668.0,3684.00,3625.00,3645.15,3652.205768,19347,1221,70659225.0,...,-118649.76,9020.52,43.57,NaN,NaN,3645.15,3650.0,3675.00,3576.20,3592.70
3,05-01-2007,1167935400,3650.0,3675.00,3576.20,3592.70,3635.146191,22970,1374,83499308.0,...,-118649.76,9020.52,43.57,NaN,NaN,3592.70,3600.0,3600.00,3505.00,3554.15
4,08-01-2007,1168194600,3600.0,3600.00,3505.00,3554.15,3550.702060,23300,1919,82731358.0,...,-118649.76,9020.52,43.57,NaN,NaN,3554.15,3570.0,3595.00,3500.00,3535.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3463,24-12-2020,1608748200,1205.0,1229.95,1191.00,1207.35,1220.311283,45306,667,55287423.0,...,-118649.76,9020.52,43.57,NaN,NaN,NaN,1225.0,1227.65,1212.00,1219.20
3464,28-12-2020,1609093800,1225.0,1227.65,1212.00,1219.20,1217.518506,6106,587,7434168.0,...,-118649.76,9020.52,43.57,NaN,NaN,NaN,1223.0,1229.10,1195.00,1204.55
3465,29-12-2020,1609180200,1223.0,1229.10,1195.00,1204.55,1212.738685,7026,727,8520702.0,...,-118649.76,9020.52,43.57,NaN,NaN,NaN,1229.0,1239.85,1203.90,1209.95
3466,30-12-2020,1609266600,1229.0,1239.85,1203.90,1209.95,1222.053157,14034,1294,17150294.0,...,-118649.76,9020.52,43.57,NaN,NaN,NaN,1212.0,1217.70,1203.55,1212.15
3467,31-12-2020,1609353000,1212.0,1217.70,1203.55,1212.15,1210.068024,7909,554,9570428.0,...,-118649.76,9020.52,43.57,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
mstock_df['Alpha'] = pd.to_numeric(mstock_df['Alpha'], errors='coerce')
mstock_df['Beta'] = pd.to_numeric(mstock_df['Beta'], errors='coerce')

In [ ]:
stock = find_gain_loss(mstock_df)
stock = close_price_as_percent_of_LV_HV_BA(stock)

C:\Users\venu\Desktop\Stock Market Analysis\GrowthRate.ipynb:50: RuntimeWarning: divide by zero encountered in double_scalars
  {

In [ ]:
stock = sequential_increase(stock)
stock = sequential_decrease(stock)

In [ ]:
stock

In [ ]:
stock = sequential_increase_percentage(stock)

In [ ]:
stock

In [ ]:
stock = sequential_decrease_percentage(stock)

In [ ]:
cols = ["Revenue","Dividend","Income","Expenditure","Net Profit","EPS"]

In [ ]:
for col in cols:
    try:
        stock = quarter_wise_growthrate(stock, col)
    except:
        pass

In [ ]:
modified_stockGR = modified_stockGR.append(stock,ignore_index=True)

In [ ]:
modified_stockGR.to_csv(os.path.join(datapath,"Stock/"+"mod"+security_id+"GR.csv"),index=None)